---
- name: Rserve
  # use apt instead of install from cran as apt has latest version
  apt: pkg={{ item }} state=present
  with_items:
    - r-cran-rserve
- name: Install Rserve init script
  template: src=rserve.service.j2 dest=/lib/systemd/system/rserve.service
- name: Start Rserve
  service: name=rserve state=started enabled=yes
  when: build_type != 'docker'
