---
- hosts: all
  roles:
    - bootstrap
    - lxde
    - knime
    - wiki
    - virtualbox-guest-additions
    - fpocket
    - r
    - self-upgrade
    - postgresql
    - rdkit
    - chembl
    - chemtools
    - cleanup
