---
- hosts: all
  roles:
    - bootstrap
    - knime
    - lxde
    - wiki
    - virtualbox-guest-additions
  tasks:
    - name: chem tools
      apt: pkg={{ item }} state=latest
      with_items:
        - openbabel
        - viewmol
        - xdrawchem
    - name: web browsers
      apt: pkg={{ item }} state=latest
      with_items:
        - firefox
        - chromium-browser
