---
- hosts: all
  vars:
    build_type: local
  roles:
    - bootstrap
    - lxde
    - knime
    - wiki
    - role: virtualbox-guest-additions
      when: build_type == 'virtualbox-iso'
    - fpocket
    - r
    - self-upgrade
    - postgresql
    - rdkit
    - chembl
    - chemtools
    - role: novnc
      when: build_type == 'docker'
    - role: entrypoint
      when: build_type == 'docker'
    - role: cleanup
      when: build_type == 'virtualbox-iso'
