---
- hosts: all
  tasks:
    # desktop
    - name: Add cinnamon desktop environment repo
      apt_repository: repo='ppa:lestcape/cinnamon' state=present update_cache=yes
    - name: ensure cinnamon desktop environment is installed
      apt: pkg=cinnamon state=latest
    - apt: pkg=mdm state=latest
    # make cinnamon start at boot
    # autologin user
    # chem tools
    - name: ensure openbabel is installed
      apt: pkg=openbabel state=latest
    # wiki
    - apt: pkg=ruby-dev state=latest
    - apt: pkg=libicu-dev state=latest
    - apt: pkg=zlib1g-dev state=latest
    - apt: pkg=build-essential state=latest
    - gem: name=gollum state=present
    - apt: pkg=git state=latest
    - git: repo=https://github.com/NLeSC/Chemical-Analytics-Platform.wiki.git dest=/opt/wiki
    # knime
    - get_url: url=http://download.knime.org/analytics-platform/linux/knime-full_2.12.0.linux.gtk.x86_64.tar.gz dest=/opt/knime.tar.gz mode=0440
    - file: path=/opt/knime state=directory mode=0755
    - unarchive: src=/opt/knime.tar.gz dest=/opt/knime copy=no creates=/opt/knime/knime-full_2.12.0
    - file: src=/opt/knime/knime-full_2.12.0/knime dest=/usr/bin/knime state=link
