---
- name: Ensure lxde desktop environment is installed
  apt: pkg=lxde state=latest
- name: Ensure lxdm is installed
  apt: pkg=lxdm state=present
- name: lxdm is running
  service: name=lxdm state=started
