---
- name: Check Knime is already installed
  stat: path='{{ knime_root }}'
  register: knime_installed
- include: install_knime.yml
  when: knime_installed.stat.islnk is not defined
- include: desktop_icon.yml
- include: more_memory.yml
- include: python_nodes.yml
- include: plugins.yml
- name: Remove old Knime installations
  file: path={{ item }} state=absent
  with-items:
    - /opt/knime/knime-full_2.12.0
    - /opt/knime/knime-full_3.1.0
- name: Vagrant owns Knime
  file: path='{{ knime_root }}' state=directory recurse=yes owner=vagrant group=vagrant
