---
- name: R ppa key
  apt_key: id="{{ cran_ppa_key }}" state=present keyserver=keyserver.ubuntu.com
- name: R ppa
  apt_repository: repo='deb http://{{ cran_ppa }}/bin/linux/ubuntu trusty/' state=present update_cache=yes
- name: R
  apt: pkg={{ item }} state=present
  with_items:
    - r-recommended
    - r-cran-rjava
    - littler
    - r-cran-rserve
- name: ggplot2 package
  shell: echo 'install.packages("ggplot2", repos="http://{{ cran_ppa }}")' | R --vanilla
  args:
    creates: /usr/local/lib/R/site-library/ggplot2
- name: Install Rserve init script
  template: src=rserve.conf.j2 dest=/etc/init/rserve.conf
- name: Start Rserve
  service: name=rserve state=started enabled=yes
